name: Android Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-tests:
    runs-on: self-hosted  # Using your connected device

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev appium wait-on allure-commandline

      - name: Fix Appium Permissions
        run: chmod +x ./node_modules/.bin/appium

      - name: Start Appium Server
        run: |
          chmod +x ./node_modules/.bin/appium
          ./node_modules/.bin/appium --port 4723 --base-path / &
          echo "Waiting for Appium to be ready..."
          npx wait-on http://localhost:4723/status

      - name: Fix WDIO permissions
        run: chmod +x ./node_modules/.bin/wdio

      - name: Prepare Screenshots Folder
        run: mkdir -p ./Screenshots

      - name: Run WDIO Android Tests
        run: ./node_modules/.bin/wdio run wdio.conf.js || true

      - name: Verify Screenshots
        run: ls -lh ./Screenshots || echo "No screenshots found"

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ./Screenshots/**/*.png
          if-no-files-found: ignore

      # Generate Allure report
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      # Upload full Allure report
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
          if-no-files-found: ignore
